#cloud-config
package_update: true
package_upgrade: true

# Instalacja niezbędnych pakietów
packages:
  - python3
  - python3-pip

write_files:
  # Tworzymy skrypt Pythona
  - path: /app/hello.py
    content: |
      import time
      import socket
      
      hostname = socket.gethostname()
      print(f"Aplikacja Python na kontenerze {hostname} wystartowała!")
      # Prosta pętla, aby proces nie zginął (np. udajemy serwer)
      while True:
          with open("/tmp/app.log", "a") as f:
              f.write(f"Dzialam... {time.ctime()}\n")
          time.sleep(10)

  # Konfigurujemy usługę systemd
  - path: /etc/systemd/system/python-app.service
    content: |
      [Unit]
      Description=Moja Automatyczna Aplikacja Python
      After=network.target

      [Service]
      ExecStart=/usr/bin/python3 /app/hello.py
      Restart=always
      User=root

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Aktywujemy usługę systemd zaraz po utworzeniu kontenera
  - systemctl daemon-reload
  - systemctl enable python-app.service
  - systemctl start python-app.service

